module.exports = {
  ar: "عربي",
  welcome: "Welcome Back!",
  login: "Login",
  log_in: "Log in",
  signup: "Signup",
  forgot: "Forgot Password?",
  reset: "Reset now",
  number: "+2 XXXXXXXX",
  username: "User Name",
  password: "Password",
  resetPassword: "Reset Password",
  save: "Save",
  confirmPassword: "Confirm Password",
  forgotPassword: "Forgot password",
  sendRequest: "Send Request",
  getAccount: "Get your own account",
  haveAccount: "You have an account?",
  verify: "Verify",
  verifyNumber: "Verify Your Number",
  code: "Code",
  findCode: "You can find the code in your SMS",
  sendAgain: "SEND AGAIN?",
  completeData: "Complete your data",
  home: "Home",
  rental: "Rental",
  featured: "Featured",
  reserve: "Reserve",
  reserve_now: "Reserve Now",
  reserve_description:
    "Most people like the idea of a Photo Booth for their upcoming events because it is fun and entertaining, but they always think all photo booth are the same – Stand in front of the machine, snap a photo and grab a print. Shutter Stop simplified the process of printing and sharing photo booth’s photos to social media instantly. It makes the photo booths connected, interactive and creates a marvelous photo experience.",
  about: "About",
  about_description:
    "Most people like the idea of a Photo Booth for their upcoming events because it is fun and entertaining, but they always think all photo booth are the same – Stand in front of the machine, snap a photo and grab a print. Shutter Stop simplified the process of printing and photo booths connected, interactive and creates a marvelous photo experience. Shutter Stop has years of experience in running photo booth related businesses. We understand the photo booth industry and how to make it better for the customers. For corporate solutions, Shutter Stop powerful engagement and marketing tool.",
  services: "Our service",
  weddings: "Weddings",
  birthdays: "Birthdays",
  events: "Events",
  our_products: "Our Products",
  photobooth: "Photobooth",
  ads: "Ads Screen",
  entertainment: "Entertainment Screen",
  smart_survey:"Smart Survey",
  live_streaming: "Live streaming",
  spin_and_win: "Spin and win",
  interactive_ads: "Interactive ads",
  interactive_videos: "Interactive videos",
  clients: "Our Clients",
  photos: "Our Photos",
  corporate: "Corporate",
  features: "Features",
  wedding: "Wedding",
  social: "Social",
  right_reserved: "All right reserved to PentaValue (C) 2021",
  portofolio: "Portofolio",
  products: "PRODUCTS",
  output: "Output",
  gifs: "GIFs",
  threed_images: "3D IMAGES",
  slow_motion: "SLOW MOTION",
  for_reservation: "For Reservation",
  name: "Name",
  email: "Email",
  phone: "Phone",
  date: "Date of event",
  address: "Address",
  package: "Package",
  note: "Note",
  send: "Send",
  core_features: "Core Features.",
  core_features_description: "Best features with the latest technologies",
};
