module.exports = {
  welcome: 'Welcome Back!',
  login: 'Login',
  log_in: 'Log in',
  signup: 'Signup',
  forgot: 'Forgot Password?',
  reset: 'Reset now',
  number: '+2 XXXXXXXX',
  username: 'User Name',
  password: 'Password',
  resetPassword: 'Reset Password',
  save: 'Save',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot password',
  sendRequest: 'Send Request',
  getAccount: 'Get your own account',
  haveAccount: 'You have an account?',
  verify: 'Verify',
  verifyNumber: 'Verify Your Number',
  code: 'Code',
  findCode: 'You can find the code in your SMS',
  sendAgain: 'SEND AGAIN?',
  completeData: 'Complete your data',
}